# Sheet 5 Exercise 16 - Resubmission
**Niklas Markert** - 1611460 / bt709885

In [1]:
import numpy as np
print(np.__version__)

1.19.2


## a)


In [5]:
v1 = np.array([1, 4, 7])
v2 = np.array([[1, 4, 7]])
v1 = np.reshape(v1, v2.shape)
print('v1: ' + str(v1))
print('v2: ' + str(v2))

v1: [[1 4 7]]
v2: [[1 4 7]]


After the use of reshape, v1, which was originally a rank 1 array, now is a rank 2 array with the same dimension
as v2. So because the values of the two arrays were the same the result after reshaping v1 looks the same as v2.

## b)

In [7]:
v = np.array([[9, 8, 7]]).T
print(v)

[[9]
 [8]
 [7]]


In [8]:
M = np.array([[3, 4], [5, 6], [7, 8]]).T
print(M)

[[3 5 7]
 [4 6 8]]


## c)

In [12]:
v1 = np.array([1, 4, 7])
print(v1==v1.transpose())
print((v1==v1.transpose()).all())

[ True  True  True]
True


Actually the code shows if a matrix (or vector) is symmetric. <br> A matrix A is symmetric, when it is the same as
its transpose, so A==A.transpose(). A vector therefore cannot be symmetric, because if you transpose a vector it
doesn't have the same shape, so it can't be identical. <br>
This code above compares the vector v1 with its transposed vector (v1T). So if v1 would be a matrix, this would be a
check if the matrix is symmetric. What the code does is, he first outputs for each value of the vectors if they are the
same as a vector of bool values. After that it outputs if they are completely the same vectors, as a single bool
value. <br>
The result of this output can be misleading, because it says that v1 and v1T would be exactly the same vectors, which
would mean that v1 is symmetric, but that's in fact not true. The reason, why it outputs that they are the same, is
that v1 is defined as a rank 1 array, which shouldn't be used for calculations. If you for example replace the v1 vector
with a rank 2 array it in fact outputs the expected results:


In [13]:
v2 = np.array([[1, 4, 7]]) # v2 now is a rank 2 array
print(v2==v2.transpose())
print((v2==v2.transpose()).all())


[[ True False False]
 [False  True False]
 [False False  True]]
False


## d)


In [23]:
v3 = np.array(['a', 1, 4.0])
print(v3[1] + v3[2])
print(type(v3[1]))

14.0
<class 'numpy.str_'>


The output of the code is '14.0', because since in the np.array is with 'a' also a String stored the other values of
the array ara also from the type numpy.str (proved by the output of the third line here). For that reasons the + between
v3[1] and v3[2] doesn't add their values, instead it concatenates the two Strings '1' and '4.0' to '14.0'


## e)

No, transpose() yield no deep copy of the matrix/vector. The following example shows, that after storing the transposed
vector of v1 in v2, changing a value of v1 also changes this value in the vector v2.

In [26]:
v1 = np.array([[1, 2, 3]])
v2 = v1.transpose()
print('v1: ' + str(v1))
print('v2: ' + str(v2))
v1[0][1] = 4
print('--Changed v1--')
print('v1: ' + str(v1))
print('v2: ' + str(v2))

v1: [[1 2 3]]
v2: [[1]
 [2]
 [3]]
--Changed v1--
v1: [[1 4 3]]
v2: [[1]
 [4]
 [3]]
