# Sheet 6 Exercise 19
**Niklas Markert** - 1611460 / bt709885 <br>
**Lukas Thiersch** - 1607110 / bt708626

In [16]:
import math

import numpy as np
import math
np.random.seed(0)

## a)


In [5]:
X = np.arange(16)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
X_sqrt = np.sqrt(X)
X_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [7]:
X_2 = np.power(X, 2)
X_2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225], dtype=int32)

In [10]:
XX = np.vstack([X_sqrt, X_2])
XX

array([[  0.        ,   1.        ,   1.41421356,   1.73205081,
          2.        ,   2.23606798,   2.44948974,   2.64575131,
          2.82842712,   3.        ,   3.16227766,   3.31662479,
          3.46410162,   3.60555128,   3.74165739,   3.87298335],
       [  0.        ,   1.        ,   4.        ,   9.        ,
         16.        ,  25.        ,  36.        ,  49.        ,
         64.        ,  81.        , 100.        , 121.        ,
        144.        , 169.        , 196.        , 225.        ]])

## b)


In [40]:
mu = 4
sigma = math.sqrt(5)
M = np.random.randn(1000, 5) * sigma + mu
M

array([[ 4.83010031,  4.6815175 ,  5.12725688,  4.30253911,  5.46184907],
       [ 3.77598777,  2.06962181,  2.26957304,  2.00916577,  4.06797418],
       [ 0.46784007, -0.20551464,  5.05451248,  5.56695603,  3.06066533],
       ...,
       [ 2.7899773 ,  4.98559508,  7.69826654,  3.55350925,  9.94027225],
       [ 4.09454977,  1.34773511,  5.50699763,  3.86975415,  4.19645005],
       [ 3.83892462,  1.80651427,  1.65546112,  4.29044924,  7.35676528]])

## c)


In [41]:
# i)
with open('file1.npy', 'wb') as f:
    np.save(f, M)

with open('file1.npy', 'rb') as f:
    M_1 = np.load(f)

M_1

array([[ 4.83010031,  4.6815175 ,  5.12725688,  4.30253911,  5.46184907],
       [ 3.77598777,  2.06962181,  2.26957304,  2.00916577,  4.06797418],
       [ 0.46784007, -0.20551464,  5.05451248,  5.56695603,  3.06066533],
       ...,
       [ 2.7899773 ,  4.98559508,  7.69826654,  3.55350925,  9.94027225],
       [ 4.09454977,  1.34773511,  5.50699763,  3.86975415,  4.19645005],
       [ 3.83892462,  1.80651427,  1.65546112,  4.29044924,  7.35676528]])

In [42]:
# ii)
with open('file2.txt', 'wb') as f:
    np.savetxt(f, M)

with open('file2.txt', 'rb') as f:
    M_2 = np.loadtxt(f)

M_2

array([[ 4.83010031,  4.6815175 ,  5.12725688,  4.30253911,  5.46184907],
       [ 3.77598777,  2.06962181,  2.26957304,  2.00916577,  4.06797418],
       [ 0.46784007, -0.20551464,  5.05451248,  5.56695603,  3.06066533],
       ...,
       [ 2.7899773 ,  4.98559508,  7.69826654,  3.55350925,  9.94027225],
       [ 4.09454977,  1.34773511,  5.50699763,  3.86975415,  4.19645005],
       [ 3.83892462,  1.80651427,  1.65546112,  4.29044924,  7.35676528]])

In my case the file1.npy as a size of 40KB in contrast to the file2.txt which has 123KB which is more than
3 times the size of the first file.


## d)


In [43]:
# minimum value
M.min(axis=0)

array([-4.92853238, -4.14665375, -3.40404927, -3.56336045, -4.00746199])

In [44]:
# maximum value
M.max(axis=0)

array([10.86565945, 11.26545761, 11.33725868, 10.17587354, 10.45679946])

In [46]:
# mean
M.mean(axis=0)

array([4.02189   , 3.97598944, 3.94854758, 4.04132272, 3.92011044])

In [47]:
# variance
M.var(axis=0)

array([5.29573092, 5.28524197, 5.37164931, 4.75554365, 4.8896342 ])

When you compare the calculated mean and variance values for each row with the parameters in b) you notice
that they are approximately the same, as they should be.


## e)

In [53]:
M2 = np.hstack([ M[:, :2], M[:, 3:] ])
M2

array([[ 4.83010031,  4.6815175 ,  4.30253911,  5.46184907],
       [ 3.77598777,  2.06962181,  2.00916577,  4.06797418],
       [ 0.46784007, -0.20551464,  5.56695603,  3.06066533],
       ...,
       [ 2.7899773 ,  4.98559508,  3.55350925,  9.94027225],
       [ 4.09454977,  1.34773511,  3.86975415,  4.19645005],
       [ 3.83892462,  1.80651427,  4.29044924,  7.35676528]])

## f)


In [54]:
M3 = M[M < 0]
M3

array([-2.05514644e-01, -7.74462368e-01, -9.60917218e-01, -1.34807365e+00,
       -7.18093573e-01, -4.54136923e-01, -4.00746199e+00, -4.62775814e-01,
       -4.66390857e-01, -1.30102900e+00, -1.03181307e+00, -1.25525519e-02,
       -2.22064667e+00, -2.49096816e+00, -3.01536005e-01, -4.88275363e-02,
       -1.05069557e+00, -8.81077523e-01, -2.41135510e+00, -1.67913678e+00,
       -6.25552325e-01, -1.03505687e+00, -2.22481480e+00, -9.84726961e-01,
       -8.66413489e-01, -6.00763820e-01, -1.65742314e+00, -6.99013121e-01,
       -4.28742310e-01, -3.43552009e-01, -2.69550393e-01, -1.94484320e-02,
       -1.37159069e+00, -9.15121027e-01, -1.99646959e+00, -4.27488364e-01,
       -2.65277485e+00, -1.61796376e+00, -2.02515365e+00, -1.97716875e+00,
       -3.40057443e+00, -6.29925128e-02, -1.46470411e-01, -1.42645507e+00,
       -2.61850902e+00, -7.34229238e-01, -1.23702400e+00, -7.61463867e-01,
       -3.61385047e-01, -2.66949837e-02, -8.20087027e-02, -5.62332024e-01,
       -4.03141018e-02, -

In [56]:
M[M > 0] = 0
M

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.20551464,  0.        ,  0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])